#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("KSI_App.Resource", IsApplication=true)]

namespace KSI_App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Halloffame = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int KSI = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int monoandroidsplash = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060007
			public const int MyButton = 2131099655;
			
			// aapt resource value: 0x7f060001
			public const int back_button = 2131099649;
			
			// aapt resource value: 0x7f06001b
			public const int cap_text = 2131099675;
			
			// aapt resource value: 0x7f06001a
			public const int cap_title = 2131099674;
			
			// aapt resource value: 0x7f060013
			public const int co_div_text = 2131099667;
			
			// aapt resource value: 0x7f060012
			public const int co_div_title = 2131099666;
			
			// aapt resource value: 0x7f060017
			public const int co_fo_text = 2131099671;
			
			// aapt resource value: 0x7f060016
			public const int co_fo_title = 2131099670;
			
			// aapt resource value: 0x7f060008
			public const int code = 2131099656;
			
			// aapt resource value: 0x7f060023
			public const int cpl_text = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int cpl_title = 2131099682;
			
			// aapt resource value: 0x7f060011
			public const int div_text = 2131099665;
			
			// aapt resource value: 0x7f060010
			public const int div_title = 2131099664;
			
			// aapt resource value: 0x7f06000a
			public const int divisions = 2131099658;
			
			// aapt resource value: 0x7f060002
			public const int editText1 = 2131099650;
			
			// aapt resource value: 0x7f060015
			public const int founder_text = 2131099669;
			
			// aapt resource value: 0x7f060014
			public const int founder_title = 2131099668;
			
			// aapt resource value: 0x7f060019
			public const int gen_text = 2131099673;
			
			// aapt resource value: 0x7f060018
			public const int gen_title = 2131099672;
			
			// aapt resource value: 0x7f06000b
			public const int hall = 2131099659;
			
			// aapt resource value: 0x7f060009
			public const int handbook = 2131099657;
			
			// aapt resource value: 0x7f060006
			public const int imageView1 = 2131099654;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int linearLayout2 = 2131099651;
			
			// aapt resource value: 0x7f060005
			public const int linearLayout3 = 2131099653;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout4 = 2131099661;
			
			// aapt resource value: 0x7f06000c
			public const int links = 2131099660;
			
			// aapt resource value: 0x7f06001d
			public const int lt_text = 2131099677;
			
			// aapt resource value: 0x7f06001c
			public const int lt_title = 2131099676;
			
			// aapt resource value: 0x7f060025
			public const int pvt_text = 2131099685;
			
			// aapt resource value: 0x7f060024
			public const int pvt_title = 2131099684;
			
			// aapt resource value: 0x7f060027
			public const int rct_text = 2131099687;
			
			// aapt resource value: 0x7f060026
			public const int rct_title = 2131099686;
			
			// aapt resource value: 0x7f060021
			public const int sgt_text = 2131099681;
			
			// aapt resource value: 0x7f060020
			public const int sgt_title = 2131099680;
			
			// aapt resource value: 0x7f06000f
			public const int sn_dir_text = 2131099663;
			
			// aapt resource value: 0x7f06000e
			public const int sn_dir_title = 2131099662;
			
			// aapt resource value: 0x7f06001f
			public const int st_sgt_text = 2131099679;
			
			// aapt resource value: 0x7f06001e
			public const int st_sgt_title = 2131099678;
			
			// aapt resource value: 0x7f060004
			public const int textView1 = 2131099652;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int code = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int divisions = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int hall = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int handbook = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int links = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Main = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int Rank = 2130903046;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040004
			public const int ApplicationName = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int Code = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int Div = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int Hall = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
